/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  target?: string
}
export function unzip(entryPath: string, options?: Options | undefined | null, signal?: AbortSignal | undefined | null): Promise<void>
export function zip(entryPath: string, options?: Options | undefined | null, signal?: AbortSignal | undefined | null): Promise<void>
